version: "3.3"
services:
  rtmp:
    container_name: rtmp_server
    build: ./base-rtmp
    ports:
      - "1935:1935"
      - "80:8080"
    volumes:
      - ./data:/tmp/hls
  auth:
    build: ./base-auth
    container_name: auth_server
